src/weather/urls.py
from django.urls import path
from .views import index, delete_city

app_name = "weather"
urlpatterns = [
    path('', index, name="home"),
    path('<int:id>/delete', delete_city, name="delete")
]

src/weather_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
]

src/weather/models.py
from os import name
from django.db import models



class City(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "cities"
    

src/weather/forms.py
from os import name
from django import forms
from django.forms import fields
from .models import City

class CityField(forms.CharField):
    def to_python(self, value):
        return value.upper()

class CityForm(forms.ModelForm):
    name = CityField(label="", widget=forms.TextInput(attrs={'placeholder': 'Type a city name'}))
    class Meta:
        model = City
        fields = ("name",)

src/weather/views.py
from os import name
from django.shortcuts import redirect, render
from decouple import config
import requests
from pprint import pprint
from .models import City
from .forms import CityForm
from django.contrib import messages

def index(request):
    form = CityForm()
    cities= City.objects.all()
    url = config('BASE_URL')
    # city = "Berlin"
    # respon = requests.get(url.format(city))
    # res = respon.json()
    # pprint(res)
    # print(type(res))
    # print(respon.text)
    if request.method == "POST":
        form = CityForm(request.POST)
        if form.is_valid():
            new_city = form.cleaned_data["name"] # => request.POST.get("name")
           
            if not City.objects.filter(name=new_city).exists():
                respon = requests.get(url.format(new_city))
                if respon.status_code == 200:
                    form.save()
                    messages.success(request, "City is added successfully!")
                else:
                    messages.warning(request, "City does not exist!!")
            else:
                messages.warning(request, "City is already exist!!")
            return redirect("weather:home")
    city_data = []
    for city in cities:
        respon = requests.get(url.format(city))
        res = respon.json()
        weather_data = {
            "city": city.name,
            "temp":res["main"]["temp"],
            "description":res["weather"][0]["description"],
            "icon":res["weather"][0]["icon"],
            "id":city.id
            
        }
        city_data.append(weather_data)
        
    context = {
        "city_data":city_data,
        "form":form
    }
    return render(request, "weather/index.html", context)


def delete_city(request, id):
    city = City.objects.get(id=id)
    if request.method == "POST":
        city.delete()
        return redirect("weather:home")

src/weather/templates/weather/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Learn Weather</title>
  </head>
  <body>
    <div class="container-fluid">
        <div class="row py-5">
            <div class="col-md-6">
                <h1 style="color: #0e3b9c;">Weather App</h1>
            </div>
            <div class="col-md-6">
                {% if messages %}
    
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
                {% endif %}
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit" class="btn btn-outline-primary" >Add</button>
                </form> <br>
            </div>

        </div>

        <div class="row ">
                        

            {% for city in city_data %}
            
            <div class="card shadow mx-auto my-4" style="width: 20rem;">
                <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image" class="card-img-top" style="height: 15rem;" alt="Weather Image">
                <div class="card-body">
                    <h5 class="card-title">{{ city.city }} </h5>
                    <p class="card-text">{{ city.temp }} <i class="fas fa-thermometer-full"></i></p>
                    <p class="card-text">{{ city.description }}</p>
                    
                  <div class="btn-group">
          
                    <!-- Open a Modal for the blog -->
                    <!-- Button To Implement the Modal-->
                    <button id = "modalToggle" type="button" class="btn btn-sm btn-outline-primary"
                        data-toggle="modal" data-target="#modal-blog-{{city.id}}">Delete</button>
                    <!-- Modal -->
                    <div class="modal fade" id="modal-blog-{{city.id}}" role="dialog">
                      <div class="modal-dialog modal-lg">
                      <div class="modal-content">
                          <div class="modal-header">
                          <h4 class="modal-title">{{ city.city }}</h4>
                          </div>
                          <div class="modal-body">
                          <p>Are you sure to delete weather informations of {{ city.city }}</p>
                          </div>
                          <div class="modal-footer">
          
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <form action="{% url 'weather:delete' city.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Yes</button>
                            </form>
          
                          </div>
                        </div>
                      </div>
                    </div>
                 </div>
               </div>
            </div>
                
            {% endfor %}
            
        </div>
    </div>
  

   
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/3af51903d1.js" crossorigin="anonymous"></script>
  </body>
</html>